# a mybinder.org-ready environment for demoing jupyterlab-tour
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   mamba env update --file binder/environment.yml
#   mamba activate jupyterlab-tour-demo
#
name: jupyterlab-tour-demo

channels:
  - conda-forge
  - nodefaults

dependencies:
  # oldest supported python
  - python ==3.10.* #  binder needs a fairly weird pin, at present
  # other language runtimes
  - nodejs 24.*
  # clients
  - jupyterlab >=4.6,<4.7
  - notebook >=7.6,<7.7
  # labextension build dependencies
  - hatch-jupyter-builder >=0.5
  - hatch-nodejs-version
  - hatchling >=1.5.0
  - pip
  - python-build
