name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MIN_PYTHON: &min-python '3.10'
  MIN_LAB: &min-lab '4.3.0'
  MIN_NB: &min-nb '7.3.0'
  MAX_LAB: &max-lab '4.6'
  MAX_NB: &max-nb '7.6'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - &step-checkout
        name: Checkout
        uses: actions/checkout@v6

      - &step-base-setup
        name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - &step-py-deps
        name: Install Python dependencies
        run: |-
          python -m pip install -v -U "jupyterlab~=${MIN_LAB}" build
          pip check

      - &step-js-cache
        name: Set up JS cache
        uses: &uses-cache actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - &step-js-deps
        name: Install JS dependencies
        run: &run-maybe-jlpm ls node_modules/.yarn-state.yml || jlpm --immutable

      - name: Package the extension
        run: pyproject-build .

      - name: Upload extension packages
        uses: actions/upload-artifact@v5
        with:
          name: &dist jpt-${{ github.run_number }}-dist
          path: dist/jupyterlab_tour*
          if-no-files-found: error

  smoke-test:
    name: Smoke Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: *min-python
          architecture: 'x64'

      - &step-download-dist
        name: Download extension package
        uses: actions/download-artifact@v6
        with:
          name: *dist

      - name: Install Extension
        run: pip install -v "jupyterlab~=${MIN_LAB}" jupyterlab_tour*.whl

      - name: Smoke Test
        run: |
          jupyter labextension list
          jupyter labextension list 2>&1 | grep -ie "jupyterlab-tour.*OK"
          python -m jupyterlab.browser_check --no-browser-test

  unit-test:
    name: Unit Test/Lint
    runs-on: ubuntu-latest
    steps:
      - *step-checkout
      - *step-base-setup
      - *step-js-cache
      - *step-py-deps
      - *step-js-deps

      - name: Lint the extension
        run: jlpm run lint:check

      - name: Test the extension
        run: jlpm run test

  ui-tests:
    name: UI tests (${{ matrix.client }} ~${{ matrix.client-version }})
    needs: [smoke-test, unit-test]
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_BROWSERS_PATH: &path-browsers ${{ github.workspace }}/pw-browsers
    strategy:
      fail-fast: false
      matrix:
        include:
          - client: jupyterlab
            client-version: *min-lab
          - client: jupyterlab
            client-version: *max-lab
          - client: notebook
            client-version: *min-nb
            jest-args: &jest-nb -c playwright-notebook.config.js
          - client: notebook
            client-version: *max-nb
            jest-args: *jest-nb
    steps:
      - *step-checkout
      - *step-base-setup
      - *step-download-dist

      - name: Set up JS cache
        uses: *uses-cache
        with:
          path: ui-tests/node_modules
          key: &key-ui-yarn-lock ${{ runner.os }}-${{ hashFiles('ui-tests/yarn.lock') }}

      - name: Set up browser cache
        uses: *uses-cache
        with:
          path: *path-browsers
          key: *key-ui-yarn-lock

      - name: Install the extension
        run: |
          set -eux
          python -m pip install "${{ matrix.client }}~=${{ matrix.client-version }}" jupyterlab_tour*.whl

      - name: Install dependencies
        working-directory: ui-tests
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: *run-maybe-jlpm

      - name: Install browser
        run: jlpm playwright install chromium
        working-directory: ui-tests

      - name: Execute integration tests
        working-directory: ui-tests
        run: |
          jlpm playwright test \
            --output test-results-${{ matrix.client }}-${{ matrix.client-version}} \
            ${{ matrix.jest-args }}

      - name: Upload Playwright Test report
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: |-
            jpt-${{ github.run_number }}-ui-tests-${{ matrix.client }}-${{ matrix.client-version }}
          path: |
            ui-tests/test-results*
            ui-tests/playwright-report

  check_links:
    name: Check Links
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - *step-checkout
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - uses: jupyterlab/maintainer-tools/.github/actions/check-links@v1
